#!/system/bin/sh
# edited by emannxperia

MAX_CPU_SPEED=1024000
MAX_CPU_SPEED_OFF=368640 
MIN_CPU_SPEED=122880
MIN_CPU_SPEED_OFF=122880

SLEEP_GOVERNOR_ON="1"

SLEEP_GOVERNOR="smartassV2"

(while [ 1 ]
do
    AWAKE=`cat /sys/power/wait_for_fb_wake`
    if [ $AWAKE = "awake" ]; then
	
    	echo $MAX_CPU_SPEED > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	    echo "Max CPUFREQ set to $MAX_CPU_SPEED"
		
	    echo $MIN_CPU_SPEED > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
	    echo "Min CPUFREQ set to $MIN_CPU_SPEED"
		
	    echo "smartassV2" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	    echo "smartassV2 Governor Set"

        AWAKE=
    fi
    SLEEPING=`cat /sys/power/wait_for_fb_sleep`
    if [ $SLEEPING = "sleeping" ]; then
	    echo $MAX_CPU_SPEED_OFF > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
	    echo $MIN_CPU_SPEED_OFF > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
	    echo "Scaling script : Min set to $MIN_CPU_SPEED_OFF, Max set to $MAX_CPU_SPEED_OFF"
		
	    if [ $SLEEP_GOVERNOR_ON = "1" ]; then
	    	echo $SLEEP_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	    	GOVERNOR=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`
	    	if [ $GOVERNOR = $SLEEP_GOVERNOR ]; then
				echo "$SLEEP_GOVERNOR Governor set"
	    	else
				echo "$SLEEP_GOVERNOR governor not set, but Min/Max OK"
			fi
	    else
	    	echo "Sleep Tweak ENABLED"
	    fi
        SLEEPING=
    fi
done &)
