#!/system/bin/sh
# edited by emannxperia

#mount tweaks
busybox mount -o remount,nosuid noatime nodiratime / -t rootfs
busybox mount -o remount,noatime nodiratime /dev -t devpts
busybox mount -o remount,noatime nodiratime /proc -t proc
busybox mount -o remount,noatime nodiratime /sys -t sysfs
busybox mount -o remount,noatime nodiratime /mnt/asec -t tmpfs
busybox mount -o remount,noatime nodiratime /mnt/sdcard -t vfat
busybox mount -o remount,noatime nodiratime /mnt/secure/asec -t vfat
busybox mount -o remount,noatime nodiratime /mnt/sdcard/.android_secure -t tmpfs

#perfect mount options
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,commit=60,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,commit=60,nobh /cache

#zdzihu_thjap_FPS Uncap and Kernel Tweaks
busybox mount -t debugfs debugfs /sys/kernel/debug
echo 0 > /sys/kernel/debug/msm_fb/0/vsync_enable
echo 0 > /sys/kernel/debug/msm_fb/0/hw_vsync_mode
echo 0 > /sys/kernel/debug/msm_fb/0/sw_refreshing_enable
echo 8 > /sys/kernel/debug/msm_fb/0/backbuff
echo 210000000 > /sys/kernel/debug/msm_fb/0/clk_rate
echo 6000 > /sys/kernel/debug/msm_fb/0/refx100
echo 400 > /sys/kernel/debug/msm_fb/mdp/mdp_usec_diff_threshold
echo 40 > /sys/kernel/debug/msm_fb/mdp/vs_rdcnt_fast
echo 40 > /sys/kernel/debug/msm_fb/mdp/vs_rdcnt_slow
echo 1 > /sys/kernel/debug/kgsl/log_level_cmd
echo 1 > /sys/kernel/debug/kgsl/log_level_ctxt
echo 1 > /sys/kernel/debug/kgsl/log_level_drv
echo 1 > /sys/kernel/debug/kgsl/log_level_mem
busybox umount /sys/kernel/debug
