#!/system/bin/sh
# edited by emannxperia and Night-Elf

echo "122880 900" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "245760 900" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "368640 900" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "460800 900" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "576000 950" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "652800 950" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "768000 950" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "806400 1000" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "921600 1050" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1024000 1050" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1113000 1100" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1209600 1150" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1305600 1200" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1401600 1200" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1516800 1250" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1612800 1250" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1708800 1300" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
echo "1804800 1300" > /sys/devices/system/cpu/cpu0/cpufreq/vdd_levels
