#!/system/bin/sh
# edited by emannxperia

if busybox [ ! -f /system/swap/swapfile.swp ]
then
	echo "Create Swapfile"
	mkdir /system/swap
	busybox dd if=/dev/zero of=/system/swap/swapfile.swp bs=1M count=32
	busybox mkswap /system/swap/swapfile.swp
	busybox chmod 0600 /system/swap/swapfile.swp
else
	echo "Swapfile Exist"
fi
echo "connect loop devices"
mknod -m640 /dev/block/loop50 b 7 50
losetup /dev/block/loop50 /system/swap/swapfile.swp
echo "use loopdev for swap"
swapon /dev/block/loop50
echo "raise swappiness 10"
#echo 90 > /proc/sys/vm/swappiness
#cat /proc/sys/vm/swappiness
free
