#!/system/bin/sh
# edited by emannxperia

#Installs BusyBox included in xbin instead of the one in ramdisk
busybox rm -rf /sbin/busybox
busybox cp /system/xbin/busybox /sbin/busybox
chmod 0777 /sbin/busybox

#Others
busybox rm -rf /res/autoroot
busybox rm -rf /sbin/autoroot.sh

#SU fixes
chmod 06755 /system/bin/su
