#!/system/bin/sh
# edited by emannxperia & Night-Elf

#SD Card & system prefetch Tweak

echo "8" > /sys/block/mtdblock0/bdi/read_ahead_kb #default 4
echo "8" > /sys/block/mtdblock1/bdi/read_ahead_kb #default 4
echo "8" > /sys/block/mtdblock2/bdi/read_ahead_kb #default 4
echo "8" > /sys/block/mtdblock3/bdi/read_ahead_kb #default 4
echo "128" > /sys/devices/virtual/bdi/7:0/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:1/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:2/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:3/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:4/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:5/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:6/read_ahead_kb #default 0
echo "128" > /sys/devices/virtual/bdi/7:7/read_ahead_kb #default 0
echo "512" > /sys/block/mmcblk0/queue/read_ahead_kb
echo "128" > /sys/block/mmcblk0/queue/max_sectors_kb
echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb #default 128
echo "256" > /sys/devices/virtual/bdi/default/read_ahead_kb #default 128
echo "97" > /sys/devices/virtual/bdi/179:0/max_ratio #default 100
echo "97" > /sys/devices/virtual/bdi/default/max_ratio #default 100

# Optimize for read- & write-throughput;
# Optimize for readahead;

for i in $STL $BML $MMC $ZRM;
do
	if [ -e $i/queue/read_ahead_kb ];
	then
		echo "1024" >  $i/queue/read_ahead_kb;
	fi;
done

#Disable iostats to reduce overhead
for k in $STL $BML $MMC $ZRM;
do
	if [ -e $k/queue/iostats ]
	then
		echo "0" > $k/queue/iostats;
	fi;
done
